# Makefile.in generated by automake 1.10.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/pam-face-authentication
pkglibdir = $(libdir)/pam-face-authentication
pkgincludedir = $(includedir)/pam-face-authentication
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-suse-linux-gnu
host_triplet = i686-suse-linux-gnu
bin_PROGRAMS = gtk-facemanager$(EXEEXT) gtk-facetracker$(EXEEXT) \
	svm-predict$(EXEEXT) svm-train$(EXEEXT) pfatrainer$(EXEEXT)
pammod_PROGRAMS = pam_face_authenticate.so$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	compile config.guess config.sub depcomp install-sh ltmain.sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(extradir)" "$(DESTDIR)$(libdir)" \
	"$(DESTDIR)$(bindir)" "$(DESTDIR)$(pammoddir)" \
	"$(DESTDIR)$(extra1dir)" "$(DESTDIR)$(uidir)"
extraLTLIBRARIES_INSTALL = $(INSTALL)
libLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(extra_LTLIBRARIES) $(lib_LTLIBRARIES)
libfaceauthenticate_la_LIBADD =
am_libfaceauthenticate_la_OBJECTS =  \
	libfaceauthenticate_la-libfaceauthenticate.lo \
	libfaceauthenticate_la-featureDctMod2.lo \
	libfaceauthenticate_la-featureLBPHist.lo \
	libfaceauthenticate_la-parseSvmPrediction.lo
libfaceauthenticate_la_OBJECTS = $(am_libfaceauthenticate_la_OBJECTS)
libfaceauthenticate_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(libfaceauthenticate_la_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
libfacedetect_la_LIBADD =
libfacedetect_la_SOURCES = libfacedetect.c
libfacedetect_la_OBJECTS = libfacedetect.lo
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
pammodPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS) $(pammod_PROGRAMS)
am_gtk_facemanager_OBJECTS = gtk-facemanagerU.$(OBJEXT) \
	featureDctMod2.$(OBJEXT) featureLBPHist.$(OBJEXT)
gtk_facemanager_OBJECTS = $(am_gtk_facemanager_OBJECTS)
am__DEPENDENCIES_1 =
gtk_facemanager_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) libfacedetect.la
gtk_facemanager_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(gtk_facemanager_LDFLAGS) $(LDFLAGS) -o $@
am_gtk_facetracker_OBJECTS = gtk-faceauthenticate.$(OBJEXT)
gtk_facetracker_OBJECTS = $(am_gtk_facetracker_OBJECTS)
gtk_facetracker_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) libfacedetect.la
gtk_facetracker_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(gtk_facetracker_LDFLAGS) $(LDFLAGS) -o $@
am_pam_face_authenticate_so_OBJECTS =  \
	pam_face_authenticate_so-pam_face_authentication.$(OBJEXT) \
	pam_face_authenticate_so-featureDctMod2.$(OBJEXT) \
	pam_face_authenticate_so-featureLBPHist.$(OBJEXT) \
	pam_face_authenticate_so-parseSvmPrediction.$(OBJEXT) \
	pam_face_authenticate_so-svm-scale.$(OBJEXT)
pam_face_authenticate_so_OBJECTS =  \
	$(am_pam_face_authenticate_so_OBJECTS)
pam_face_authenticate_so_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) libfacedetect.la \
	libfaceauthenticate.la
pam_face_authenticate_so_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(pam_face_authenticate_so_CFLAGS) $(CFLAGS) \
	$(pam_face_authenticate_so_LDFLAGS) $(LDFLAGS) -o $@
am_pfatrainer_OBJECTS = svm-scale.$(OBJEXT) svm.$(OBJEXT) \
	libsvm-train.$(OBJEXT) trainer.$(OBJEXT)
pfatrainer_OBJECTS = $(am_pfatrainer_OBJECTS)
pfatrainer_LDADD = $(LDADD)
am_svm_predict_OBJECTS = svm-predict.$(OBJEXT) svm.$(OBJEXT)
svm_predict_OBJECTS = $(am_svm_predict_OBJECTS)
svm_predict_LDADD = $(LDADD)
am_svm_train_OBJECTS = svm-train.$(OBJEXT) svm.$(OBJEXT)
svm_train_OBJECTS = $(am_svm_train_OBJECTS)
svm_train_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libfaceauthenticate_la_SOURCES) libfacedetect.c \
	$(gtk_facemanager_SOURCES) $(gtk_facetracker_SOURCES) \
	$(pam_face_authenticate_so_SOURCES) $(pfatrainer_SOURCES) \
	$(svm_predict_SOURCES) $(svm_train_SOURCES)
DIST_SOURCES = $(libfaceauthenticate_la_SOURCES) libfacedetect.c \
	$(gtk_facemanager_SOURCES) $(gtk_facetracker_SOURCES) \
	$(pam_face_authenticate_so_SOURCES) $(pfatrainer_SOURCES) \
	$(svm_predict_SOURCES) $(svm_train_SOURCES)
extra1DATA_INSTALL = $(INSTALL_DATA)
uiDATA_INSTALL = $(INSTALL_DATA)
DATA = $(extra1_DATA) $(ui_DATA)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication/missing --run aclocal-1.10
AMTAR = ${SHELL} /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication/missing --run autoconf
AUTOHEADER = ${SHELL} /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication/missing --run autoheader
AUTOMAKE = ${SHELL} /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication/missing --run automake-1.10
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = gfortran
FFLAGS = -g -O2
GREP = /usr/bin/grep
GSL_CFLAGS = -I/usr/local/include  
GSL_LIBS = -L/usr/local/lib -lgsl -lgslcblas -lm  
GTK_CFLAGS = -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng12  
GTK_LIBS = -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lpango-1.0 -lcairo -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0  
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lpam -lpam 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NMEDIT = 
OBJEXT = o
OPENCV_CFLAGS = -I/usr/local/include/opencv  
OPENCV_LIBS = -L/usr/local/lib -lcxcore -lcv -lhighgui -lcvaux -lml  
PACKAGE = pam-face-authentication
PACKAGE_BUGREPORT = http://code.google.com/p/pam_face_authentication/issues/list
PACKAGE_NAME = pam-face-authentication
PACKAGE_STRING = pam-face-authentication 0.3
PACKAGE_TARNAME = pam-face-authentication
PACKAGE_VERSION = 0.3
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.3
X11_LIBS = -lX11
abs_builddir = /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication
abs_srcdir = /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication
abs_top_builddir = /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication
abs_top_srcdir = /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = gfortran
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-suse-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = suse
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-suse-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = suse
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /home/darksid3hack0r/Desktop/pam-face-authentication/pam_face_authentication/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_builddir = .
top_srcdir = .
DEBUG = -g
INCLUDES = \
	-DVERSION=\".3\" \
	-DPKGDATADIR=\"$(pkgdatadir)\" \
	-DBINDIR=\"$(bindir)\" \
	$(GTK_CFLAGS) \
	$(X11_CFLAGS) \
	$(GSL_CFLAGS) \
	$(OPENCV_CFLAGS)

pfatrainer_SOURCES = ./libsvm/svm.h \
			./libsvm/svm-scale.c \
                        ./libsvm/svm.cpp \
			 ./libsvm/libsvm-train.c \
			trainer.c

svm_predict_SOURCES = ./libsvm/svm-predict.c \
		      ./libsvm/svm.h \
		      ./libsvm/svm.cpp

svm_train_SOURCES = ./libsvm/svm-train.c \
			./libsvm/svm.h \
			./libsvm/svm.cpp

gtk_facemanager_SOURCES = gtk-facemanagerU.c \
			featureDctMod2.c \
			featureLBPHist.c

gtk_facemanager_LDADD = \
	$(GTK_LIBS) \
	$(GSL_LIBS) \
	$(OPENCV_LIBS) \
	libfacedetect.la

gtk_facemanager_LDFLAGS = -export-dynamic
gtk_facetracker_SOURCES = gtk-faceauthenticate.c
gtk_facetracker_LDADD = \
			$(GTK_LIBS) \
			$(GSL_LIBS) \
			$(OPENCV_LIBS) \
			libfacedetect.la

gtk_facetracker_LDFLAGS = -export-dynamic
extradir = $(prefix)/lib/
lib_LTLIBRARIES = libfaceauthenticate.la
extra_LTLIBRARIES = libfacedetect.la 
libfaceauthenticate_la_SOURCES = libfaceauthenticate.c \
				featureDctMod2.c \
				featureLBPHist.c \
				parseSvmPrediction.c

libfaceauthenticate_la_CFLAGS = $(AM_CFLAGS)
pammoddir = /lib/security
pam_face_authenticate_so_SOURCES = \
	pam_face_authentication.c \
	pam_face.h \
	featureDctMod2.c \
	featureLBPHist.c \
	parseSvmPrediction.c \
	./libsvm/svm-scale.c \
	pam_face_defines.h

pam_face_authenticate_so_CFLAGS = -L/usr/X11R6/lib -lX11 -fPIC
pam_face_authenticate_so_LDFLAGS = -shared 
pam_face_authenticate_so_LDADD = \
                        $(PAM_LIBS) \
                        $(GSL_LIBS) \
                        $(OPENCV_LIBS) \
		           $(X11_LIBS) \
			libfacedetect.la \
                        libfaceauthenticate.la

extra1dir = /etc/pam-face-authentication/
extra1_DATA = xauth.key display.key prediction db.lst
uidir = $(pkgdatadir)
ui_DATA = \
gtk-faceauthenticate.xml \
gtk-facemanager.xml \
gtk-facemanagerU.xml \
haarcascade_eye.xml \
haarcascade_nose.xml \
haarcascade.xml

EXTRA_DIST = $(ui_DATA) $(extra1_DATA)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-extraLTLIBRARIES: $(extra_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(extradir)" || $(MKDIR_P) "$(DESTDIR)$(extradir)"
	@list='$(extra_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(extraLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(extradir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(extraLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(extradir)/$$f"; \
	  else :; fi; \
	done

uninstall-extraLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(extra_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(extradir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(extradir)/$$p"; \
	done

clean-extraLTLIBRARIES:
	-test -z "$(extra_LTLIBRARIES)" || rm -f $(extra_LTLIBRARIES)
	@list='$(extra_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(libdir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(libdir)/$$f"; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$p"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libfaceauthenticate.la: $(libfaceauthenticate_la_OBJECTS) $(libfaceauthenticate_la_DEPENDENCIES) 
	$(libfaceauthenticate_la_LINK) -rpath $(libdir) $(libfaceauthenticate_la_OBJECTS) $(libfaceauthenticate_la_LIBADD) $(LIBS)
libfacedetect.la: $(libfacedetect_la_OBJECTS) $(libfacedetect_la_DEPENDENCIES) 
	$(LINK) -rpath $(extradir) $(libfacedetect_la_OBJECTS) $(libfacedetect_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
install-pammodPROGRAMS: $(pammod_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(pammoddir)" || $(MKDIR_P) "$(DESTDIR)$(pammoddir)"
	@list='$(pammod_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(pammodPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(pammoddir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(pammodPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(pammoddir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-pammodPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(pammod_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(pammoddir)/$$f'"; \
	  rm -f "$(DESTDIR)$(pammoddir)/$$f"; \
	done

clean-pammodPROGRAMS:
	@list='$(pammod_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
gtk-facemanager$(EXEEXT): $(gtk_facemanager_OBJECTS) $(gtk_facemanager_DEPENDENCIES) 
	@rm -f gtk-facemanager$(EXEEXT)
	$(gtk_facemanager_LINK) $(gtk_facemanager_OBJECTS) $(gtk_facemanager_LDADD) $(LIBS)
gtk-facetracker$(EXEEXT): $(gtk_facetracker_OBJECTS) $(gtk_facetracker_DEPENDENCIES) 
	@rm -f gtk-facetracker$(EXEEXT)
	$(gtk_facetracker_LINK) $(gtk_facetracker_OBJECTS) $(gtk_facetracker_LDADD) $(LIBS)
pam_face_authenticate.so$(EXEEXT): $(pam_face_authenticate_so_OBJECTS) $(pam_face_authenticate_so_DEPENDENCIES) 
	@rm -f pam_face_authenticate.so$(EXEEXT)
	$(pam_face_authenticate_so_LINK) $(pam_face_authenticate_so_OBJECTS) $(pam_face_authenticate_so_LDADD) $(LIBS)
pfatrainer$(EXEEXT): $(pfatrainer_OBJECTS) $(pfatrainer_DEPENDENCIES) 
	@rm -f pfatrainer$(EXEEXT)
	$(CXXLINK) $(pfatrainer_OBJECTS) $(pfatrainer_LDADD) $(LIBS)
svm-predict$(EXEEXT): $(svm_predict_OBJECTS) $(svm_predict_DEPENDENCIES) 
	@rm -f svm-predict$(EXEEXT)
	$(CXXLINK) $(svm_predict_OBJECTS) $(svm_predict_LDADD) $(LIBS)
svm-train$(EXEEXT): $(svm_train_OBJECTS) $(svm_train_DEPENDENCIES) 
	@rm -f svm-train$(EXEEXT)
	$(CXXLINK) $(svm_train_OBJECTS) $(svm_train_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/featureDctMod2.Po
include ./$(DEPDIR)/featureLBPHist.Po
include ./$(DEPDIR)/gtk-faceauthenticate.Po
include ./$(DEPDIR)/gtk-facemanagerU.Po
include ./$(DEPDIR)/libfaceauthenticate_la-featureDctMod2.Plo
include ./$(DEPDIR)/libfaceauthenticate_la-featureLBPHist.Plo
include ./$(DEPDIR)/libfaceauthenticate_la-libfaceauthenticate.Plo
include ./$(DEPDIR)/libfaceauthenticate_la-parseSvmPrediction.Plo
include ./$(DEPDIR)/libfacedetect.Plo
include ./$(DEPDIR)/libsvm-train.Po
include ./$(DEPDIR)/pam_face_authenticate_so-featureDctMod2.Po
include ./$(DEPDIR)/pam_face_authenticate_so-featureLBPHist.Po
include ./$(DEPDIR)/pam_face_authenticate_so-pam_face_authentication.Po
include ./$(DEPDIR)/pam_face_authenticate_so-parseSvmPrediction.Po
include ./$(DEPDIR)/pam_face_authenticate_so-svm-scale.Po
include ./$(DEPDIR)/svm-predict.Po
include ./$(DEPDIR)/svm-scale.Po
include ./$(DEPDIR)/svm-train.Po
include ./$(DEPDIR)/svm.Po
include ./$(DEPDIR)/trainer.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

libfaceauthenticate_la-libfaceauthenticate.lo: libfaceauthenticate.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -MT libfaceauthenticate_la-libfaceauthenticate.lo -MD -MP -MF $(DEPDIR)/libfaceauthenticate_la-libfaceauthenticate.Tpo -c -o libfaceauthenticate_la-libfaceauthenticate.lo `test -f 'libfaceauthenticate.c' || echo '$(srcdir)/'`libfaceauthenticate.c
	mv -f $(DEPDIR)/libfaceauthenticate_la-libfaceauthenticate.Tpo $(DEPDIR)/libfaceauthenticate_la-libfaceauthenticate.Plo
#	source='libfaceauthenticate.c' object='libfaceauthenticate_la-libfaceauthenticate.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -c -o libfaceauthenticate_la-libfaceauthenticate.lo `test -f 'libfaceauthenticate.c' || echo '$(srcdir)/'`libfaceauthenticate.c

libfaceauthenticate_la-featureDctMod2.lo: featureDctMod2.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -MT libfaceauthenticate_la-featureDctMod2.lo -MD -MP -MF $(DEPDIR)/libfaceauthenticate_la-featureDctMod2.Tpo -c -o libfaceauthenticate_la-featureDctMod2.lo `test -f 'featureDctMod2.c' || echo '$(srcdir)/'`featureDctMod2.c
	mv -f $(DEPDIR)/libfaceauthenticate_la-featureDctMod2.Tpo $(DEPDIR)/libfaceauthenticate_la-featureDctMod2.Plo
#	source='featureDctMod2.c' object='libfaceauthenticate_la-featureDctMod2.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -c -o libfaceauthenticate_la-featureDctMod2.lo `test -f 'featureDctMod2.c' || echo '$(srcdir)/'`featureDctMod2.c

libfaceauthenticate_la-featureLBPHist.lo: featureLBPHist.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -MT libfaceauthenticate_la-featureLBPHist.lo -MD -MP -MF $(DEPDIR)/libfaceauthenticate_la-featureLBPHist.Tpo -c -o libfaceauthenticate_la-featureLBPHist.lo `test -f 'featureLBPHist.c' || echo '$(srcdir)/'`featureLBPHist.c
	mv -f $(DEPDIR)/libfaceauthenticate_la-featureLBPHist.Tpo $(DEPDIR)/libfaceauthenticate_la-featureLBPHist.Plo
#	source='featureLBPHist.c' object='libfaceauthenticate_la-featureLBPHist.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -c -o libfaceauthenticate_la-featureLBPHist.lo `test -f 'featureLBPHist.c' || echo '$(srcdir)/'`featureLBPHist.c

libfaceauthenticate_la-parseSvmPrediction.lo: parseSvmPrediction.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -MT libfaceauthenticate_la-parseSvmPrediction.lo -MD -MP -MF $(DEPDIR)/libfaceauthenticate_la-parseSvmPrediction.Tpo -c -o libfaceauthenticate_la-parseSvmPrediction.lo `test -f 'parseSvmPrediction.c' || echo '$(srcdir)/'`parseSvmPrediction.c
	mv -f $(DEPDIR)/libfaceauthenticate_la-parseSvmPrediction.Tpo $(DEPDIR)/libfaceauthenticate_la-parseSvmPrediction.Plo
#	source='parseSvmPrediction.c' object='libfaceauthenticate_la-parseSvmPrediction.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfaceauthenticate_la_CFLAGS) $(CFLAGS) -c -o libfaceauthenticate_la-parseSvmPrediction.lo `test -f 'parseSvmPrediction.c' || echo '$(srcdir)/'`parseSvmPrediction.c

pam_face_authenticate_so-pam_face_authentication.o: pam_face_authentication.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-pam_face_authentication.o -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-pam_face_authentication.Tpo -c -o pam_face_authenticate_so-pam_face_authentication.o `test -f 'pam_face_authentication.c' || echo '$(srcdir)/'`pam_face_authentication.c
	mv -f $(DEPDIR)/pam_face_authenticate_so-pam_face_authentication.Tpo $(DEPDIR)/pam_face_authenticate_so-pam_face_authentication.Po
#	source='pam_face_authentication.c' object='pam_face_authenticate_so-pam_face_authentication.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-pam_face_authentication.o `test -f 'pam_face_authentication.c' || echo '$(srcdir)/'`pam_face_authentication.c

pam_face_authenticate_so-pam_face_authentication.obj: pam_face_authentication.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-pam_face_authentication.obj -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-pam_face_authentication.Tpo -c -o pam_face_authenticate_so-pam_face_authentication.obj `if test -f 'pam_face_authentication.c'; then $(CYGPATH_W) 'pam_face_authentication.c'; else $(CYGPATH_W) '$(srcdir)/pam_face_authentication.c'; fi`
	mv -f $(DEPDIR)/pam_face_authenticate_so-pam_face_authentication.Tpo $(DEPDIR)/pam_face_authenticate_so-pam_face_authentication.Po
#	source='pam_face_authentication.c' object='pam_face_authenticate_so-pam_face_authentication.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-pam_face_authentication.obj `if test -f 'pam_face_authentication.c'; then $(CYGPATH_W) 'pam_face_authentication.c'; else $(CYGPATH_W) '$(srcdir)/pam_face_authentication.c'; fi`

pam_face_authenticate_so-featureDctMod2.o: featureDctMod2.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-featureDctMod2.o -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-featureDctMod2.Tpo -c -o pam_face_authenticate_so-featureDctMod2.o `test -f 'featureDctMod2.c' || echo '$(srcdir)/'`featureDctMod2.c
	mv -f $(DEPDIR)/pam_face_authenticate_so-featureDctMod2.Tpo $(DEPDIR)/pam_face_authenticate_so-featureDctMod2.Po
#	source='featureDctMod2.c' object='pam_face_authenticate_so-featureDctMod2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-featureDctMod2.o `test -f 'featureDctMod2.c' || echo '$(srcdir)/'`featureDctMod2.c

pam_face_authenticate_so-featureDctMod2.obj: featureDctMod2.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-featureDctMod2.obj -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-featureDctMod2.Tpo -c -o pam_face_authenticate_so-featureDctMod2.obj `if test -f 'featureDctMod2.c'; then $(CYGPATH_W) 'featureDctMod2.c'; else $(CYGPATH_W) '$(srcdir)/featureDctMod2.c'; fi`
	mv -f $(DEPDIR)/pam_face_authenticate_so-featureDctMod2.Tpo $(DEPDIR)/pam_face_authenticate_so-featureDctMod2.Po
#	source='featureDctMod2.c' object='pam_face_authenticate_so-featureDctMod2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-featureDctMod2.obj `if test -f 'featureDctMod2.c'; then $(CYGPATH_W) 'featureDctMod2.c'; else $(CYGPATH_W) '$(srcdir)/featureDctMod2.c'; fi`

pam_face_authenticate_so-featureLBPHist.o: featureLBPHist.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-featureLBPHist.o -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-featureLBPHist.Tpo -c -o pam_face_authenticate_so-featureLBPHist.o `test -f 'featureLBPHist.c' || echo '$(srcdir)/'`featureLBPHist.c
	mv -f $(DEPDIR)/pam_face_authenticate_so-featureLBPHist.Tpo $(DEPDIR)/pam_face_authenticate_so-featureLBPHist.Po
#	source='featureLBPHist.c' object='pam_face_authenticate_so-featureLBPHist.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-featureLBPHist.o `test -f 'featureLBPHist.c' || echo '$(srcdir)/'`featureLBPHist.c

pam_face_authenticate_so-featureLBPHist.obj: featureLBPHist.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-featureLBPHist.obj -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-featureLBPHist.Tpo -c -o pam_face_authenticate_so-featureLBPHist.obj `if test -f 'featureLBPHist.c'; then $(CYGPATH_W) 'featureLBPHist.c'; else $(CYGPATH_W) '$(srcdir)/featureLBPHist.c'; fi`
	mv -f $(DEPDIR)/pam_face_authenticate_so-featureLBPHist.Tpo $(DEPDIR)/pam_face_authenticate_so-featureLBPHist.Po
#	source='featureLBPHist.c' object='pam_face_authenticate_so-featureLBPHist.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-featureLBPHist.obj `if test -f 'featureLBPHist.c'; then $(CYGPATH_W) 'featureLBPHist.c'; else $(CYGPATH_W) '$(srcdir)/featureLBPHist.c'; fi`

pam_face_authenticate_so-parseSvmPrediction.o: parseSvmPrediction.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-parseSvmPrediction.o -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-parseSvmPrediction.Tpo -c -o pam_face_authenticate_so-parseSvmPrediction.o `test -f 'parseSvmPrediction.c' || echo '$(srcdir)/'`parseSvmPrediction.c
	mv -f $(DEPDIR)/pam_face_authenticate_so-parseSvmPrediction.Tpo $(DEPDIR)/pam_face_authenticate_so-parseSvmPrediction.Po
#	source='parseSvmPrediction.c' object='pam_face_authenticate_so-parseSvmPrediction.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-parseSvmPrediction.o `test -f 'parseSvmPrediction.c' || echo '$(srcdir)/'`parseSvmPrediction.c

pam_face_authenticate_so-parseSvmPrediction.obj: parseSvmPrediction.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-parseSvmPrediction.obj -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-parseSvmPrediction.Tpo -c -o pam_face_authenticate_so-parseSvmPrediction.obj `if test -f 'parseSvmPrediction.c'; then $(CYGPATH_W) 'parseSvmPrediction.c'; else $(CYGPATH_W) '$(srcdir)/parseSvmPrediction.c'; fi`
	mv -f $(DEPDIR)/pam_face_authenticate_so-parseSvmPrediction.Tpo $(DEPDIR)/pam_face_authenticate_so-parseSvmPrediction.Po
#	source='parseSvmPrediction.c' object='pam_face_authenticate_so-parseSvmPrediction.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-parseSvmPrediction.obj `if test -f 'parseSvmPrediction.c'; then $(CYGPATH_W) 'parseSvmPrediction.c'; else $(CYGPATH_W) '$(srcdir)/parseSvmPrediction.c'; fi`

pam_face_authenticate_so-svm-scale.o: ./libsvm/svm-scale.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-svm-scale.o -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-svm-scale.Tpo -c -o pam_face_authenticate_so-svm-scale.o `test -f './libsvm/svm-scale.c' || echo '$(srcdir)/'`./libsvm/svm-scale.c
	mv -f $(DEPDIR)/pam_face_authenticate_so-svm-scale.Tpo $(DEPDIR)/pam_face_authenticate_so-svm-scale.Po
#	source='./libsvm/svm-scale.c' object='pam_face_authenticate_so-svm-scale.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-svm-scale.o `test -f './libsvm/svm-scale.c' || echo '$(srcdir)/'`./libsvm/svm-scale.c

pam_face_authenticate_so-svm-scale.obj: ./libsvm/svm-scale.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -MT pam_face_authenticate_so-svm-scale.obj -MD -MP -MF $(DEPDIR)/pam_face_authenticate_so-svm-scale.Tpo -c -o pam_face_authenticate_so-svm-scale.obj `if test -f './libsvm/svm-scale.c'; then $(CYGPATH_W) './libsvm/svm-scale.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-scale.c'; fi`
	mv -f $(DEPDIR)/pam_face_authenticate_so-svm-scale.Tpo $(DEPDIR)/pam_face_authenticate_so-svm-scale.Po
#	source='./libsvm/svm-scale.c' object='pam_face_authenticate_so-svm-scale.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(pam_face_authenticate_so_CFLAGS) $(CFLAGS) -c -o pam_face_authenticate_so-svm-scale.obj `if test -f './libsvm/svm-scale.c'; then $(CYGPATH_W) './libsvm/svm-scale.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-scale.c'; fi`

svm-scale.o: ./libsvm/svm-scale.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT svm-scale.o -MD -MP -MF $(DEPDIR)/svm-scale.Tpo -c -o svm-scale.o `test -f './libsvm/svm-scale.c' || echo '$(srcdir)/'`./libsvm/svm-scale.c
	mv -f $(DEPDIR)/svm-scale.Tpo $(DEPDIR)/svm-scale.Po
#	source='./libsvm/svm-scale.c' object='svm-scale.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o svm-scale.o `test -f './libsvm/svm-scale.c' || echo '$(srcdir)/'`./libsvm/svm-scale.c

svm-scale.obj: ./libsvm/svm-scale.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT svm-scale.obj -MD -MP -MF $(DEPDIR)/svm-scale.Tpo -c -o svm-scale.obj `if test -f './libsvm/svm-scale.c'; then $(CYGPATH_W) './libsvm/svm-scale.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-scale.c'; fi`
	mv -f $(DEPDIR)/svm-scale.Tpo $(DEPDIR)/svm-scale.Po
#	source='./libsvm/svm-scale.c' object='svm-scale.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o svm-scale.obj `if test -f './libsvm/svm-scale.c'; then $(CYGPATH_W) './libsvm/svm-scale.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-scale.c'; fi`

libsvm-train.o: ./libsvm/libsvm-train.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libsvm-train.o -MD -MP -MF $(DEPDIR)/libsvm-train.Tpo -c -o libsvm-train.o `test -f './libsvm/libsvm-train.c' || echo '$(srcdir)/'`./libsvm/libsvm-train.c
	mv -f $(DEPDIR)/libsvm-train.Tpo $(DEPDIR)/libsvm-train.Po
#	source='./libsvm/libsvm-train.c' object='libsvm-train.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libsvm-train.o `test -f './libsvm/libsvm-train.c' || echo '$(srcdir)/'`./libsvm/libsvm-train.c

libsvm-train.obj: ./libsvm/libsvm-train.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libsvm-train.obj -MD -MP -MF $(DEPDIR)/libsvm-train.Tpo -c -o libsvm-train.obj `if test -f './libsvm/libsvm-train.c'; then $(CYGPATH_W) './libsvm/libsvm-train.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/libsvm-train.c'; fi`
	mv -f $(DEPDIR)/libsvm-train.Tpo $(DEPDIR)/libsvm-train.Po
#	source='./libsvm/libsvm-train.c' object='libsvm-train.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libsvm-train.obj `if test -f './libsvm/libsvm-train.c'; then $(CYGPATH_W) './libsvm/libsvm-train.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/libsvm-train.c'; fi`

svm-predict.o: ./libsvm/svm-predict.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT svm-predict.o -MD -MP -MF $(DEPDIR)/svm-predict.Tpo -c -o svm-predict.o `test -f './libsvm/svm-predict.c' || echo '$(srcdir)/'`./libsvm/svm-predict.c
	mv -f $(DEPDIR)/svm-predict.Tpo $(DEPDIR)/svm-predict.Po
#	source='./libsvm/svm-predict.c' object='svm-predict.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o svm-predict.o `test -f './libsvm/svm-predict.c' || echo '$(srcdir)/'`./libsvm/svm-predict.c

svm-predict.obj: ./libsvm/svm-predict.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT svm-predict.obj -MD -MP -MF $(DEPDIR)/svm-predict.Tpo -c -o svm-predict.obj `if test -f './libsvm/svm-predict.c'; then $(CYGPATH_W) './libsvm/svm-predict.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-predict.c'; fi`
	mv -f $(DEPDIR)/svm-predict.Tpo $(DEPDIR)/svm-predict.Po
#	source='./libsvm/svm-predict.c' object='svm-predict.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o svm-predict.obj `if test -f './libsvm/svm-predict.c'; then $(CYGPATH_W) './libsvm/svm-predict.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-predict.c'; fi`

svm-train.o: ./libsvm/svm-train.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT svm-train.o -MD -MP -MF $(DEPDIR)/svm-train.Tpo -c -o svm-train.o `test -f './libsvm/svm-train.c' || echo '$(srcdir)/'`./libsvm/svm-train.c
	mv -f $(DEPDIR)/svm-train.Tpo $(DEPDIR)/svm-train.Po
#	source='./libsvm/svm-train.c' object='svm-train.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o svm-train.o `test -f './libsvm/svm-train.c' || echo '$(srcdir)/'`./libsvm/svm-train.c

svm-train.obj: ./libsvm/svm-train.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT svm-train.obj -MD -MP -MF $(DEPDIR)/svm-train.Tpo -c -o svm-train.obj `if test -f './libsvm/svm-train.c'; then $(CYGPATH_W) './libsvm/svm-train.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-train.c'; fi`
	mv -f $(DEPDIR)/svm-train.Tpo $(DEPDIR)/svm-train.Po
#	source='./libsvm/svm-train.c' object='svm-train.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o svm-train.obj `if test -f './libsvm/svm-train.c'; then $(CYGPATH_W) './libsvm/svm-train.c'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm-train.c'; fi`

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

svm.o: ./libsvm/svm.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT svm.o -MD -MP -MF $(DEPDIR)/svm.Tpo -c -o svm.o `test -f './libsvm/svm.cpp' || echo '$(srcdir)/'`./libsvm/svm.cpp
	mv -f $(DEPDIR)/svm.Tpo $(DEPDIR)/svm.Po
#	source='./libsvm/svm.cpp' object='svm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o svm.o `test -f './libsvm/svm.cpp' || echo '$(srcdir)/'`./libsvm/svm.cpp

svm.obj: ./libsvm/svm.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT svm.obj -MD -MP -MF $(DEPDIR)/svm.Tpo -c -o svm.obj `if test -f './libsvm/svm.cpp'; then $(CYGPATH_W) './libsvm/svm.cpp'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm.cpp'; fi`
	mv -f $(DEPDIR)/svm.Tpo $(DEPDIR)/svm.Po
#	source='./libsvm/svm.cpp' object='svm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o svm.obj `if test -f './libsvm/svm.cpp'; then $(CYGPATH_W) './libsvm/svm.cpp'; else $(CYGPATH_W) '$(srcdir)/./libsvm/svm.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
install-extra1DATA: $(extra1_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(extra1dir)" || $(MKDIR_P) "$(DESTDIR)$(extra1dir)"
	@list='$(extra1_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(extra1DATA_INSTALL) '$$d$$p' '$(DESTDIR)$(extra1dir)/$$f'"; \
	  $(extra1DATA_INSTALL) "$$d$$p" "$(DESTDIR)$(extra1dir)/$$f"; \
	done

uninstall-extra1DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(extra1_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(extra1dir)/$$f'"; \
	  rm -f "$(DESTDIR)$(extra1dir)/$$f"; \
	done
install-uiDATA: $(ui_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(uidir)" || $(MKDIR_P) "$(DESTDIR)$(uidir)"
	@list='$(ui_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(uiDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(uidir)/$$f'"; \
	  $(uiDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(uidir)/$$f"; \
	done

uninstall-uiDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(ui_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(uidir)/$$f'"; \
	  rm -f "$(DESTDIR)$(uidir)/$$f"; \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonemtpy = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(DATA) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(extradir)" "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pammoddir)" "$(DESTDIR)$(extra1dir)" "$(DESTDIR)$(uidir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-extraLTLIBRARIES clean-generic \
	clean-libLTLIBRARIES clean-libtool clean-pammodPROGRAMS \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am: install-extra1DATA install-extraLTLIBRARIES \
	install-pammodPROGRAMS install-uiDATA

install-dvi: install-dvi-am

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-extra1DATA \
	uninstall-extraLTLIBRARIES uninstall-libLTLIBRARIES \
	uninstall-pammodPROGRAMS uninstall-uiDATA

.MAKE: install-am install-exec-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-extraLTLIBRARIES clean-generic \
	clean-libLTLIBRARIES clean-libtool clean-pammodPROGRAMS ctags \
	dist dist-all dist-bzip2 dist-gzip dist-lzma dist-shar \
	dist-tarZ dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-exec-hook \
	install-extra1DATA install-extraLTLIBRARIES install-html \
	install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man install-pammodPROGRAMS \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip install-uiDATA installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-extra1DATA \
	uninstall-extraLTLIBRARIES uninstall-libLTLIBRARIES \
	uninstall-pammodPROGRAMS uninstall-uiDATA


install-exec-hook:
		   chown root $(bindir)/pfatrainer
		   chmod u+s $(bindir)/pfatrainer
		   chown root $(bindir)/svm-predict
		   chmod u+s $(bindir)/svm-predict
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
