/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include "cv.h"
#include "highgui.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include <time.h>
#include <ctype.h>


#include <dlfcn.h>


#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <unistd.h>
#include <gtk/gtk.h>
#include "interface.h"
#include "support.h"

CvCapture* capture = 0;
IplImage *frame, *frame_copy = 0;

void *handleFaceDetect;
void (*faceDetect)(IplImage*,CvPoint*,CvPoint*,CvMemStorage*,CvHaarClassifierCascade*);
void (*saveFace)(IplImage*,CvPoint*,CvPoint*,char*,char*);


void *handleFaceConfigure;
void (*learn)();


//  FACE DETECTION
static CvMemStorage* storage = 0;
static CvHaarClassifierCascade* cascade = 0;
   CvPoint p1;
   CvPoint p2;
 GdkPixbuf *pixbuf = NULL;
 GdkPixbuf *pixbufUserFace = NULL;
unsigned char *gdata;

extern   GtkWidget *webcamImage;
extern    GtkWidget *userList;
        unsigned char *shared; /* pointer to the shm */
        int shmid;
        key_t ipckey;
static gboolean
time_handler(GtkWidget *widget)
{
  if (widget->window == NULL) return FALSE;
  static CvScalar colors[] =
    {
        {{0,0,255}},
        {{0,128,255}},
        {{0,255,255}},
        {{0,255,0}},
        {{255,128,0}},
        {{255,255,0}},
        {{255,0,0}},
        {{255,0,255}}
    };



            if( !cvGrabFrame( capture ))
                return FALSE;
            frame = cvRetrieveFrame( capture );
            if( !frame )
               return FALSE;
            if( !frame_copy )
                frame_copy = cvCreateImage( cvSize(frame->width,frame->height),
                                            IPL_DEPTH_8U, frame->nChannels );
            if( frame->origin == IPL_ORIGIN_TL )
                cvCopy( frame, frame_copy, 0 );
            else
                cvFlip( frame, frame_copy, 0 );
                   cvClearMemStorage( storage );
         faceDetect(frame_copy,&p1,&p2,storage,cascade);
   cvRectangle(frame_copy,p1,p2,colors[3],3,4,0);
if( cvWaitKey( 4 ) >= 0 )
{}

if(pixbuf!=NULL)
{
gdata = gdk_pixbuf_get_pixels(pixbuf);
int m,n,o;
for(n=0;n<240;n++)
 {
for(m= 0;m<320;m++)
 {

     CvScalar s;
s=cvGet2D(frame_copy,n,m);

gdata[n*960 + m*3 +0]=(uchar)s.val[2];
gdata[n*960 + m*3 +1]=(uchar)s.val[1];
gdata[n*960 + m*3 +2]=(uchar)s.val[0];
 }
 }

  gtk_image_set_from_pixbuf(webcamImage, pixbuf);


}
   //



 return TRUE;
}
void populateUserList()
{
char tempUserName[512];
char imgFilename[512];
FILE* file1;

if (file1 = fopen("/lib/pamface/facemanager/face.key", "r"))
	{
while(fscanf(file1,"%s %s", tempUserName, imgFilename)!=EOF )
	{
 char *text[2];
    char *b="Assigned";
text[0]=tempUserName;
text[1]=b;
if(strlen(text[0])>0)
gtk_clist_append(GTK_CLIST(userList),(gchar**)text);




	}
	}


}


int
main (int argc, char *argv[])
{

// DLOPEN libfacedetect which contains the face detection related methods

handleFaceDetect = dlopen("/lib/pamface/libfacedetect.so", RTLD_NOW);
faceDetect = dlsym(handleFaceDetect, "faceDetect");
saveFace = dlsym(handleFaceDetect, "saveFace");
// DLOPEN ENDS HERE

// DLOPEN libfaceconfigure

handleFaceConfigure = dlopen("/lib/pamface/facemanager/libfaceconfigure.so", RTLD_NOW);
learn = dlsym(handleFaceConfigure, "learn");
// DLOPEN ENDS HERE


//  DETECTED FACE CORDINATES

   cascade = (CvHaarClassifierCascade*)cvLoad( "/lib/pamface/haarcascade.xml", 0, 0, 0 );
    storage = cvCreateMemStorage(0);
////

  GtkWidget *faceManager;
  GtkWidget *removeUserPrompt;
   GtkWidget *userNamePrompt;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  faceManager = create_faceManager ();
    removeUserPrompt = create_removeUserPrompt ();
      userNamePrompt = create_userNamePrompt();
  gtk_widget_show (faceManager);
  capture = cvCaptureFromCAM(0);
  pixbuf = gdk_pixbuf_new(GDK_COLORSPACE_RGB, FALSE,8,320,240);
  pixbufUserFace = gdk_pixbuf_new(GDK_COLORSPACE_RGB, FALSE,8,92,112);
populateUserList();
  g_timeout_add(100, (GSourceFunc) time_handler, (gpointer) faceManager);
  time_handler(g_timeout_add);
  gtk_main ();
   cvReleaseImage( &frame_copy );
          cvReleaseCapture( &capture );
  return 0;
}

