/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif



#include <gtk/gtk.h>
#include <time.h>
#include "interface.h"
#include "support.h"
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>

#include <stdio.h>
#include <stdlib.h>

#include <time.h>
extern   GtkWidget *webcamImage;
extern   GtkWidget *information;
        unsigned char *shared; /* pointer to the shm */
        int shmid;
        key_t ipckey;
static gboolean
time_handler(GtkWidget *widget)
{
  if (widget->window == NULL) return FALSE;
        pid_t pid;


 GdkPixbuf *pixbuf = NULL;
pixbuf = gdk_pixbuf_new(GDK_COLORSPACE_RGB, FALSE,8,320,240);
unsigned char *gdata;
if(pixbuf!=NULL)
{
gdata = gdk_pixbuf_get_pixels(pixbuf);
int m,n,o;
for(n=0;n<240;n++)
 {
for(m= 0;m<320;m++)
 {

//s=cvGet2D(img,i,j); // get the (i,j) pixel value
gdata[n*960 + m*3 +0]=(unsigned char)*(shared + m*3 + 2+ n*320*3);
gdata[n*960 + m*3 +1]=(unsigned char)*(shared + m*3 + 1+ n*320*3);

gdata[n*960 + m*3 +2]=(unsigned char)*(shared + m*3 + 0+ n*320*3);

 }
 }

  gtk_image_set_from_pixbuf(webcamImage, pixbuf);


}
   time_t simple_time;
        struct tm *time_info;
 gchar *str = g_new(gchar, 25);
   /* get simple time and convert it into a tm structure */
        time (&simple_time);
        time_info = localtime(&simple_time);

        /* %X = Preferred time of day representation for current locale. */

        strftime(str, 25, "%X", time_info);
  gtk_label_set_text(GTK_LABEL(information), str);
    g_free(str);


  return TRUE;
}
int
main (int argc, char *argv[])
{

 ipckey = 567814;
 shmid = shmget(ipckey, 230400, IPC_CREAT | 0666);
 shared = shmat(shmid, NULL, 0);


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gtk_facetracker = create_gtk_facetracker ();
  gtk_widget_show (gtk_facetracker);
  g_timeout_add(100, (GSourceFunc) time_handler, (gpointer) gtk_facetracker);
  time_handler(g_timeout_add);


  gtk_main ();
  return 0;
}

